modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="corn_delight"
version="${file.jarVersion}"
displayName="Corn Delight"
logoFile="logo.png"
credits="Farmer's Delight Group"
authors="MCMOD Modding Group"
description='''
Do you like Corn?
Now Corn in Farmer's Delight!
'''

[[dependencies.corn_delight]] 
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.18.2-1.2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="mmlib"
    mandatory=true
    versionRange="[1.1.3-1.18.2,)"
    ordering="AFTER"
    side="BOTH"
