modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="corn_delight"
version="${file.jarVersion}"
displayName="Corn Delight"
logoFile="logo.png"
credits="Farmer's Delight Group"
authors="MCMOD Modding Group"
description='''
Do you like Corn?
Now Corn in Farmer's Delight!
'''

[[dependencies.corn_delight]] 
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.20.1-1.2.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="mysterious_mountain_lib"
    mandatory=true
    versionRange="[1.5.15-1.20.1,)"
    ordering="AFTER"
    side="BOTH"
