modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
credits="Farmer's Delight Group"
authors="${mod_authors}"
description='''
Do you like Corn?
Now Corn in Farmer's Delight!
'''

[[dependencies.corn_delight]] 
    modId="neoforge" 
    type="required" 
    versionRange="${neo_version_range}" 
    ordering="NONE"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.4a,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.corn_delight]]
    modId="mysterious_mountain_lib"
    mandatory=true
    versionRange="[1.0.0-1.21,)"
    ordering="AFTER"
    side="BOTH"
